name: twenty

services:
  server:
    build:
      context: "../../"
      dockerfile: "./packages/twenty-docker/twenty/Dockerfile"
      args:
        GERALT_SECRET: ${GERALT_SECRET}
    image: twentycrm/twenty:${TAG:-latest}
    ports:
      - "3000:3000"
    environment:
      SERVER_URL: ${SERVER_URL}
      APP_SECRET: ${APP_SECRET:-replace_me_with_a_random_string}
    restart: always

  worker:
    build:
      context: "../../"
      dockerfile: "./packages/twenty-docker/twenty/Dockerfile"
      args:
        GERALT_SECRET: ${GERALT_SECRET}
    image: twentycrm/twenty:${TAG:-latest}
    command: ["yarn", "worker:prod"]
    environment:
      SERVER_URL: ${SERVER_URL}
      APP_SECRET: ${APP_SECRET:-replace_me_with_a_random_string}
    restart: always

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${PG_DATABASE_PASSWORD:-postgres}
    restart: always

  redis:
    image: redis
    restart: always

volumes:
  server-local-data:
